language: node_js
node_js:
  - "16"
install:
  - yarn install
  - yarn global add codecov
jobs:
  include:
    - stage: Unit Tests
      script: yarn test --coverage && codecov
    - stage: Lint
      script: yarn lint
    - stage: Publish npm package
      script: yarn build
